version: '3.8'

networks:
  cluster-network:
    driver: bridge

services:
  # Servidor Web Next.js (TypeScript / App Router)
  next-app:
    build:
      context: ./next-app
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://sam_admin:bomber_password@postgres-db:5432/telemetry_db
    networks:
      - cluster-network
    depends_on:
      - postgres-db

  # Motor de Base de Datos PostgreSQL 16 + Script de Inicialización Automatizado
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sam_admin
      - POSTGRES_PASSWORD=bomber_password
      - POSTGRES_DB=telemetry_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cluster-network

  # Panel de Administración Gráfica para PostgreSQL
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-panel
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=sam@univalle.edu.co
      - PGADMIN_DEFAULT_PASSWORD=admin_password
    networks:
      - cluster-network
    depends_on:
      - postgres-db

  # Entorno de Ciencia de Datos e Inteligencia Artificial
  jupyterlab:
    image: jupyter/scipy-notebook:latest
    container_name: jupyter-ia
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=sam_secret_token
    networks:
      - cluster-network

volumes:
  pgdata:
